# AI Configuration for KiroCLI
# Set your API keys as environment variables:
# export OPENAI_API_KEY="your-key-here"
# export ANTHROPIC_API_KEY="your-key-here"
# export GOOGLE_API_KEY="your-key-here"

default_provider: openai
default_model: gpt-4

providers:
  openai:
    models:
      - gpt-4
      - gpt-3.5-turbo
    temperature: 0.7
    max_tokens: 2000
  
  claude:
    models:
      - claude-3-sonnet-20240229
      - claude-3-haiku-20240307
    temperature: 0.7
    max_tokens: 2000
  
  gemini:
    models:
      - gemini-pro
      - gemini-pro-vision
    temperature: 0.7
    max_tokens: 2000